language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - py.test --cov-report=

notifications:
  email:
    - programmer.zhx@gmail.com
    - guangyizhang.jan@gmail.com
